/**
 * What `/api/admin/insight` constructs, so `route.ts` constructs nothing.
 * **A7, 2026-07-31.**
 *
 * ── A THIRD `shared.ts`, AND IT IS THE SURFACE'S CONVENTION RATHER THAN COPY-PASTE ──
 *
 * `users/shared.ts` and `blog/shared.ts` exist for the same reason and each says so:
 * the genuinely common parts (`requireAdmin`, `adminNotFound`) come from A1's
 * `@/lib/admin/identity`, and what stays local is the response vocabulary of one route
 * tree. Importing `../blog/shared` would drag `LintViolation` and a 422 shape that has
 * nothing to do with an insight, and A6 declined the same import from the other
 * direction.
 *
 * **THE REASON THIS FILE MUST EXIST AT ALL IS A FENCE**, not taste:
 * `page.contract.test.ts` asserts that no `route.ts` anywhere under `src/app/api/admin`
 * imports `next/server` or writes a bare `NextResponse.json(` — so the header lives in
 * one place and a handler cannot forget it. That fence is A5's and it binds whoever adds
 * a route next, which is the whole point of it globbing the tree rather than A5's own
 * files.
 */
import { NextResponse } from 'next/server';
import { adminNotFound, requireAdmin } from '@/lib/admin/identity';

export { adminNotFound, requireAdmin };

/** No shared cache and no history entry. An insight is per-operator and per-range and
 *  is regenerated by a button, so a cached copy would be a stale paragraph under a
 *  timestamp saying otherwise. */
export const NO_STORE = { 'cache-control': 'private, no-store' } as const;

export type InsightResponse =
  | {
      status: 'ok' | 'unchanged';
      body: string;
      inputHash: string;
      /**
       * ISO. **The server never formats a date for a client component** — the box does
       * it with `stamp()`, whose zone is pinned, because two formatters would disagree
       * about the zone and React cannot patch a text mismatch during hydration.
       */
      updatedAt: string;
    }
  | {
      status: 'error';
      /** Every value here needs a sentence in `INSIGHT.error`, or `readResponse` narrows
       *  it to `failed` and the box tells the operator the wrong thing. `'tally'` joined
       *  on 2026-08-01 with the anti-recital check. */
      reason: 'failed' | 'empty' | 'too-long' | 'format' | 'tally' | 'ceiling' | 'unavailable';
    };

export function ok(body: InsightResponse, status = 200): NextResponse {
  return NextResponse.json(body, { status, headers: NO_STORE });
}

/** The database did not answer. **Never the driver's words** — see `route.ts`'s catch. */
export function unavailable(): NextResponse {
  return NextResponse.json({ status: 'error', reason: 'unavailable' } satisfies InsightResponse, {
    status: 503,
    headers: NO_STORE,
  });
}

/**
 * **A METHOD MISMATCH MUST 404, NOT 405** (A-D2). Next answers 405 at the ROUTING layer
 * from the set of exported verbs, before the handler runs, so `requireAdmin()` never
 * executes and no gate in the file can prevent it — one reliable bit per unimplemented
 * verb telling a signed-in non-admin that this route exists. `HEAD` is absent because
 * Next derives it from `GET`, which is exported.
 */
export const refuseMethod = async (): Promise<NextResponse> => adminNotFound();
