import type { LoreDoc } from '@/content/types';

/**
 * Judgement (XX), Indonesian. THE SOURCE DOCUMENT OF THE PAIR.
 *
 * Research, confirmed before writing:
 *   - Pluto (the SECOND of the two modern planets in this deck -- The Hanged Man
 *     is the other); Hebrew letter Shin (the tooth); Golden Dawn title "Spirit of
 *     the Primal Fire".
 *     https://angelorum.co/topics/divination/golden-dawn-astrologica/
 *   - **`Judgement`, NEVER `Judgment`**, and `judgement` in the URL. The card
 *     spells it that way and so does §3.2's table.
 *   - Rider-Waite: an angel with a trumpet above, figures rising from open coffins
 *     below, arms raised.
 *   - Our painting (`public/cards/20_judgement.webp`): a great winged figure blows
 *     a long horn above a FLOODED graveyard; the dead climb out of open stone
 *     graves with their arms up; a ruined city stands on the horizon; the water
 *     between the graves is dark red.
 *
 * **THE ELEMENT DISAGREEMENT IS REAL AND IS THIS DOCUMENT'S ANCHOR.**
 * `cards.json` gives this trump `water`; the Golden Dawn attributes it to FIRE,
 * and its own title says Primal Fire. Both facts are true and the page renders
 * OURS. **Do not "fix" `cards.json`** -- it is generated by a script S4 does not
 * own and the reading prompt has consumed `element` since the first release.
 * `correspondence.test.ts` asserts the element only for the twelve SIGN cards for
 * exactly this reason; the nine planetary ones are editorial.
 *
 * MALAY CHECK: none of the eleven. `kamu` throughout. NO THERAPY OR DIAGNOSIS.
 *
 * ENGINE: **polarity `neutral`, which does not flip.** yesno `yes` -> `no`.
 * Root card: `reduce(20)` is 2, The High Priestess.
 */
export const judgementId: LoreDoc = {
  slug: 'judgement',
  locale: 'id',
  cardId: 20,
  anchor: 'element',

  title: 'Arti Kartu Judgement (XX) — Tarot Major Arcana',
  description:
    'Judgement (XX) adalah panggilan yang harus kamu jawab. Arti tegak, terbalik, ' +
    'dan kenapa unsurnya air sementara tradisi menyebutnya api.',
  h1: 'Arti Kartu Judgement (XX)',
  standfirst:
    'Kartu kedua puluh Major Arcana. Bukan kartu penghakiman — kartu panggilan ' +
    'yang menyebut namamu, dan yang tidak menunggu kamu merasa pantas.',
  imageAlt:
    'Sesosok bersayap besar meniup terompet panjang di atas pekuburan yang ' +
    'tergenang; orang-orang mati memanjat keluar dari makam batu yang terbuka ' +
    'dengan tangan terangkat, dan sebuah kota runtuh berdiri di kejauhan.',

  upright: [
    {
      kind: 'paragraph',
      text:
        'Tegak, Judgement bukan penilaian atas dirimu. Dia panggilan, dan panggilan ' +
        'punya sifat yang berbeda dari penilaian: dia menyebut namamu, dan setelah ' +
        'itu diam saja sudah termasuk jawaban.',
    },
    {
      kind: 'paragraph',
      text:
        'Yang membuatnya berat adalah waktunya. Panggilan ini hampir tidak pernah ' +
        'datang pada saat kamu merasa siap, dan tidak ada mekanisme untuk memintanya ' +
        'datang lagi nanti. Yang ada cuma dijawab atau tidak dijawab.',
    },
    {
      kind: 'paragraph',
      text:
        'Muatannya netral, dan itu tepat. Kartu ini tidak mengatakan bahwa menjawab ' +
        'akan berakhir baik. Dia mengatakan bahwa pertanyaannya sudah diajukan, dan ' +
        'itu sudah mengubah keadaanmu apa pun yang kamu putuskan.',
    },
  ],

  reversed: [
    {
      kind: 'paragraph',
      text:
        'Terbalik, panggilan yang terus kamu tunda. Muatannya tetap netral — jangan ' +
        'membacanya sebagai versi yang lebih berat — dan yang berubah cuma berapa ' +
        'lama sudah.',
    },
    {
      kind: 'paragraph',
      text:
        'Menunda panggilan jarang terasa seperti menolak. Terasanya seperti belum ' +
        'sempat, dan alasannya nyata setiap kali: ada pekerjaan, ada keadaan, ada ' +
        'satu hal lain yang lebih mendesak. Semuanya benar, dan panggilannya tetap ' +
        'belum dijawab.',
    },
    {
      kind: 'paragraph',
      text:
        'Jawabannya membalik jadi tidak, dan yang ditolak bukan panggilan itu. Yang ' +
        'ditolak adalah menunggu satu kondisi lagi sebelum menjawab, karena kondisi ' +
        'itu sudah beberapa kali diganti.',
    },
  ],

  yesno: {
    upright: 'yes',
    reversed: 'no',
    note:
      'Tegak, ya, dan ya yang tidak menunggu kesiapanmu: panggilannya sudah ' +
      'terdengar dan diam sudah termasuk jawaban. Terbalik jadi tidak — yang ' +
      'ditolak adalah satu syarat lagi sebelum menjawab.',
  },

  lore: [
    { kind: 'heading', level: 2, text: 'Air di kartu kami, api dalam tradisi' },
    {
      kind: 'paragraph',
      text:
        'Data kartu ini menyebut unsurnya air. Susunan Golden Dawn menyebut trump ' +
        'kedua puluh sebagai api, dan judul yang mereka berikan padanya adalah Spirit ' +
        'of the Primal Fire. Keduanya benar, dan halaman ini memakai yang kami pakai.',
    },
    {
      kind: 'paragraph',
      text:
        'Perbedaan itu bukan kesalahan yang perlu dirapikan. Data kartu inilah yang ' +
        'dibaca oleh seluruh aplikasi ini sejak rilis pertama, jadi mengubahnya demi ' +
        'kecocokan dengan tabel lama akan mengubah setiap bacaan yang pernah dibuat.',
    },
    {
      kind: 'paragraph',
      text:
        'Dan air masuk akal untuk gambar ini. Pekuburannya tergenang. Yang naik naik ' +
        'dari bawah air, bukan dari api.',
    },

    { kind: 'heading', level: 2, text: 'Shin, gigi' },
    {
      kind: 'paragraph',
      text:
        'Hurufnya Shin, yang berarti gigi, dan yang dalam tradisi dikaitkan dengan ' +
        'api. Bentuk hurufnya sendiri sering dibaca sebagai tiga lidah api. Di sinilah ' +
        'api yang disebut Golden Dawn itu sebetulnya berada: di hurufnya, bukan di ' +
        'gambarnya.',
    },
    {
      kind: 'paragraph',
      text:
        'Planetnya Pluto, dan ini yang kedua dari dua tempat tumpukan ini memakai ' +
        'planet modern — yang satu lagi The Hanged Man. Pluto baru ditemukan pada ' +
        'tahun 1930, jadi tabel yang lebih tua tidak memuatnya sama sekali, dan ' +
        'sumber-sumbernya memang berbeda pendapat tentang kartu ini.',
    },

    { kind: 'heading', level: 2, text: 'Terompet, dan air yang gelap' },
    {
      kind: 'paragraph',
      text:
        'Di kartu kami sosok bersayapnya besar sekali dan meniup terompet panjang. Di ' +
        'bawahnya makam-makam batu sudah terbuka dan orang-orang memanjat keluar ' +
        'dengan tangan terangkat.',
    },
    {
      kind: 'paragraph',
      text:
        'Airnya menggenang di antara makam dan warnanya gelap. Di kejauhan ada kota ' +
        'yang sudah runtuh. Panggilan ini tidak datang ke tempat yang masih utuh; dia ' +
        'datang ke tempat yang sudah selesai.',
    },
    {
      kind: 'paragraph',
      text:
        'Tidak ada satu pun sosok di bawah yang sedang ditimbang. Tidak ada timbangan ' +
        'di gambar ini. Yang ada cuma bunyi, dan orang-orang yang bangun.',
    },

    { kind: 'heading', level: 2, text: 'Dua puluh, dan akarnya' },
    {
      kind: 'paragraph',
      text:
        'Dua puluh dilipat menjadi dua, dan dua adalah The High Priestess. Pasangan ' +
        'itu bagus sekali: kartu tentang sesuatu yang sudah kamu tahu dan belum kamu ' +
        'ucapkan berdiri tepat di belakang kartu tentang panggilan yang harus ' +
        'dijawab.',
    },
    { kind: 'cardRef', slug: 'the-high-priestess', text: 'Baca lore The High Priestess (II)' },
  ],

  inSpread: [
    {
      kind: 'paragraph',
      text:
        'Di Kartu Harian, dia biasanya menunjuk pada satu pesan yang belum kamu balas ' +
        'dan yang sudah terlalu lama, dan yang membalasnya akan mengubah sesuatu.',
    },
    {
      kind: 'paragraph',
      text:
        'Di bacaan tiga kartu, di posisi yang menanti di depan dia bukan ramalan ' +
        'hasil. Dia menandai bahwa pertanyaannya akan diajukan kepadamu secara ' +
        'langsung, dan bahwa menghindar akan berhenti jadi pilihan.',
    },
  ],

  questions: [
    {
      q: 'Judgement berarti saya akan dinilai?',
      a:
        'Tidak. Tidak ada timbangan di kartu ini — itu Justice. Yang ada di sini ' +
        'bunyi terompet dan orang-orang yang bangun, dan yang diminta cuma satu: ' +
        'menjawab.',
    },
    {
      q: 'Kenapa ejaannya Judgement dan bukan Judgment?',
      a:
        'Karena kartunya mengeja begitu, dan alamat halamannya mengikuti. Ejaan ' +
        'Inggris yang lebih tua ini yang dipakai di hampir semua tumpukan tarot, ' +
        'termasuk yang ini.',
    },
    {
      q: 'Unsurnya air atau api?',
      a:
        'Data kartu kami menyebut air dan tradisi Golden Dawn menyebut api. Halaman ' +
        'ini memakai air karena itu yang dibaca seluruh aplikasi, dan menyebutkan ' +
        'yang lain karena menyembunyikannya akan tidak jujur.',
    },
    {
      q: 'Terbalik, bagaimana kalau saya memang belum siap?',
      a:
        'Kartu ini tidak menghitung kesiapan, dan itu bagian dari isinya. Yang dia ' +
        'tanyakan bukan apakah kamu pantas, melainkan apakah kamu menjawab — dan ' +
        'menunda sudah beberapa kali diberi syarat baru.',
    },
  ],
};

export default judgementId;
