import { bullets, cardRef, em, h2, h3, link, para, s, steps, strong } from '../blocks';
import type { BlogDoc } from '../types';

/**
 * `how-to-read-tarot`, Indonesian. **THE SOURCE ARTICLE.**
 *
 * The English companion at `./how-to-read-tarot.en.ts` is AUTHORED, not translated
 * (roadmap §8.2). It opens differently, teaches the single-card draw first, corrects a
 * different set of myths, and works its example on different cards — and
 * `blog.content.test.ts` asserts the two documents share no worked-example card, so a
 * future translation is a red test rather than a reviewer's judgement call.
 *
 * MALAY CHECK: no `kerana`, `iaitu`, `manakala`, `tempoh`, `awak`, `kerjaya`,
 * `hala tuju`. `karena` throughout, `kamu` throughout. The eleven-word grep runs on this
 * file twice — once through `blog.content.test.ts`'s typed walk and once through
 * `src/content/copy.test.ts`'s string-literal scan.
 *
 * NOTHING HERE DESCRIBES THE PRODUCT. No prompt layer, no persona construction, no
 * memory features, no derived verdict, and no statement that a reading is generated by a
 * model — `/terms` 4.3 discloses that where disclosure belongs. What is written here is
 * the method any tarot book from the last century would recognise.
 *
 * THE ANCHOR IDS ARE ENGLISH IN BOTH LOCALES, and `what-tarot-is` / `myths-and-facts` /
 * `what-its-for` are an INTERFACE. Renaming one breaks a link for the reader who knows
 * least, which is exactly the reader those sections exist for. Same discipline as
 * `Clause id="6-2"`.
 *
 * **THE TWO ASIDES ARE PARAGRAPHS AND NOT A `callout`.** S6 asked for a sixth block kind
 * for exactly this register and reconciliation R16 refused it, on S6's own recommendation
 * that it was the ask to refuse first. Read them: they carry their own emphasis and lose
 * nothing.
 */
export const howToReadTarotId: BlogDoc = {
  slug: 'how-to-read-tarot',
  locale: 'id',
  title: 'Cara Membaca Kartu Tarot: Panduan Pemula yang Jujur',
  description:
    'Cara membaca kartu tarot dari nol: menyiapkan kartu, menyusun pertanyaan, sebaran tiga kartu, arti kartu terbalik, dan kesalahan yang paling sering terjadi.',
  hero: { cardUrlSlug: 'the-hermit', alt: 'The Hermit' },
  body: [
    h2('what-tarot-is', 'Apa itu tarot, sebenarnya'),
    para(
      s(
        'Tarot adalah setumpuk kartu bergambar. Itu saja — dan itu sudah cukup untuk membuat orang memakainya selama lima ratus tahun. Setumpuk lengkap berisi 78 kartu: 56 kartu Minor Arcana yang tersusun dalam empat rangkaian, dan 22 kartu Major Arcana yang berdiri sendiri, dari The Fool sampai The World.',
      ),
    ),
    para(
      s(
        'Yang membuat tarot bertahan selama itu bukan kemampuannya meramal. Yang membuatnya bertahan adalah bahasanya. Dua puluh dua gambar Major Arcana memuat hampir semua hal besar yang bisa terjadi pada seseorang — jatuh cinta, kehilangan, keberanian yang datang terlambat, kebohongan yang akhirnya terbuka, perubahan yang tidak kamu minta — dalam bentuk yang bisa kamu tunjuk dengan jari.',
      ),
    ),
    para(
      s(
        'Jadi membaca tarot bukan membuka sandi. Membaca tarot berarti melihat gambar, menyebut apa yang kamu lihat, lalu menghubungkannya dengan pertanyaan yang kamu bawa. Bagian tersulitnya bukan hafalan. Bagian tersulitnya adalah jujur pada apa yang muncul, termasuk ketika yang muncul bukan yang kamu harapkan.',
      ),
    ),
    para(
      s(
        'Panduan ini memakai 22 Major Arcana saja, dan itu bukan penyederhanaan yang malas. Dua puluh dua kartu cukup sedikit untuk dikenali satu per satu dalam beberapa minggu, dan cukup besar untuk menjawab hampir semua pertanyaan yang benar-benar mengganggu seseorang. Kalau kamu ingin pengenalan yang lebih pelan, mulailah dari ',
      ),
      link('/blog/what-tarot-is', 'apa itu tarot dan untuk apa'),
      s(', lalu kembali ke sini.'),
    ),

    h2('myths-and-facts', 'Mitos dan fakta'),
    para(
      s(
        'Hampir semua yang orang tahu tentang tarot datang dari film. Enam koreksi, dan yang pertama adalah yang paling penting.',
      ),
    ),
    bullets(
      [
        strong('Mitos: tarot meramal masa depan.'),
        s(
          ' Tarot tidak memberi tahu apa yang akan terjadi. Tarot menunjukkan apa yang sedang bergerak sekarang, dan ke mana arahnya kalau tidak ada yang berubah. Itu perbedaan antara ramalan dan cermin, dan seluruh sisa panduan ini berdiri di atasnya.',
        ),
      ],
      [
        strong('Mitos: kartu Death berarti kematian.'),
        s(
          ' Death hampir selalu berarti sesuatu yang sudah selesai dan tidak akan kembali: sebuah pekerjaan, sebuah kebiasaan, satu versi dirimu yang sudah kamu lewati. Kartu yang paling ditakuti dalam setumpuk justru salah satu yang paling sering melegakan.',
        ),
      ],
      [
        strong('Mitos: kartu terbalik berarti sial.'),
        s(' Kartu terbalik mengucapkan hal yang '),
        em('berbeda'),
        s(', bukan hal yang buruk. Bagian '),
        link('#reversals', 'tentang kartu terbalik'),
        s(' menjelaskan alasannya.'),
      ],
      [
        strong('Mitos: kamu harus punya bakat khusus.'),
        s(
          ' Yang dibutuhkan adalah perhatian, kejujuran, dan latihan yang membosankan. Sama seperti belajar membaca partitur: mula-mula kamu mengeja, lalu suatu hari kamu tidak mengeja lagi.',
        ),
      ],
      [
        strong('Mitos: setumpuk kartu harus hadiah dari orang lain.'),
        s(
          ' Itu kebiasaan yang manis, bukan aturan. Beli sendiri setumpuk yang gambarnya kamu sukai; kamu akan menatapnya lama sekali.',
        ),
      ],
      [
        strong('Mitos: satu kartu punya satu arti tetap.'),
        s(
          ' Arti sebuah kartu bergerak menurut pertanyaannya dan menurut kartu di sebelahnya. Daftar arti kartu adalah titik awal, bukan kamus — kartu yang sama bisa berarti "sabar" pada satu bacaan dan "kamu sedang menunda" pada bacaan berikutnya.',
        ),
      ],
    ),
    para(
      strong('Satu aturan yang bukan mitos:'),
      s(
        ' jangan membaca kartu untuk orang yang tidak memintanya. Membaca tanpa diminta, lalu menyampaikan hasilnya, adalah cara memaksa seseorang mendengar pendapatmu tentang hidupnya dengan pembungkus yang terlihat netral.',
      ),
    ),

    h2('what-its-for', 'Untuk apa tarot dipakai'),
    para(
      s(
        'Ada tiga hal yang tarot lakukan dengan baik, dan satu hal yang sebaiknya tidak kamu minta darinya.',
      ),
    ),
    para(
      strong('Memberi bentuk pada sesuatu yang belum punya bentuk.'),
      s(
        ' Ada perasaan yang belum sempat kamu namai. Sebuah gambar memberi kamu pegangan untuk menamainya, dan begitu sesuatu punya nama, ia bisa dibicarakan.',
      ),
    ),
    para(
      strong('Memaksa kamu menyebut pertanyaanmu dengan kalimat lengkap.'),
      s(
        ' Ini efek yang paling sering diremehkan. Untuk menarik kartu, kamu harus lebih dulu memutuskan apa yang sebenarnya kamu tanyakan — dan sering kali pekerjaan itu sudah menyelesaikan separuh masalahnya sebelum kartu pertama dibuka.',
      ),
    ),
    para(
      strong('Memberi kosakata untuk hal yang kamu sudah tahu.'),
      s(
        ' Kebanyakan bacaan yang terasa tepat tidak memberi kabar baru. Ia menyebut sesuatu yang sudah kamu ketahui dan belum kamu ucapkan, dengan kata-kata yang cukup asing sehingga kamu tidak bisa mengabaikannya lagi.',
      ),
    ),
    para(
      strong('Dan yang sebaiknya tidak:'),
      s(
        ' keputusan yang seharusnya diambil dengan angka, dokumen, atau nasihat orang yang memang ahlinya. Tarot bukan pengganti nasihat medis, hukum, atau keuangan, dan tidak pernah berpura-pura begitu. Kalau sebuah pertanyaan punya jawaban yang bisa dicari, cari jawabannya.',
      ),
    ),

    h2('preparing', 'Menyiapkan kartu dan diri sendiri'),
    para(
      s(
        'Tidak ada ritual yang wajib. Yang ada hanya beberapa kebiasaan yang membuat bacaan lebih mudah dipercaya oleh dirimu sendiri, dan itu satu-satunya kepercayaan yang perlu dijaga.',
      ),
    ),
    steps(
      [
        s(
          'Cari tempat yang tidak akan mengganggumu selama sepuluh menit. Matikan pemberitahuan di ponsel.',
        ),
      ],
      [
        s(
          'Kocok kartu sambil memikirkan pertanyaanmu. Tidak ada cara mengocok yang benar; berhentilah ketika kamu merasa cukup, bukan setelah hitungan tertentu.',
        ),
      ],
      [
        s(
          'Belah setumpuknya sekali, dengan tangan yang tidak kamu pakai menulis. Alasannya bukan mistis: gerakan yang sedikit asing memaksa kamu memperhatikan apa yang sedang kamu lakukan.',
        ),
      ],
      [
        s('Tentukan sebarannya '),
        em('sebelum'),
        s(
          ' menarik kartu. Menentukan arti posisi setelah melihat kartunya adalah cara paling halus untuk membaca apa yang kamu inginkan.',
        ),
      ],
      [
        s(
          'Letakkan kartu tertutup, lalu buka satu per satu. Bicarakan kartu pertama sampai selesai sebelum membuka yang kedua.',
        ),
      ],
    ),

    h2('the-question', 'Menyusun pertanyaan yang bisa dijawab'),
    para(
      s(
        'Pertanyaan yang bagus itu terbuka, spesifik, dan tentang dirimu sendiri. Tiga syarat, dan yang ketiga paling sering dilanggar.',
      ),
    ),
    para(
      s(
        'Perhatikan tiga pasang di bawah ini. Bentuk yang pertama hanya bisa dijawab "ya" atau "tidak", dan setumpuk kartu bergambar adalah alat yang buruk untuk menjawab "ya" atau "tidak". Bentuk yang kedua bisa dijawab dengan gambar.',
      ),
    ),
    bullets(
      [
        em('"Apakah dia mencintaiku?"'),
        s(' menjadi '),
        strong('"Apa yang perlu aku lihat tentang hubungan ini sekarang?"'),
      ],
      [
        em('"Kapan aku dapat pekerjaan?"'),
        s(' menjadi '),
        strong('"Apa yang menahan lamaran-lamaranku, dan apa yang masih bisa aku ubah?"'),
      ],
      [
        em('"Aku harus pindah kota atau tidak?"'),
        s(' menjadi '),
        strong('"Apa yang aku dapat kalau pindah, dan apa yang aku tinggalkan di sini?"'),
      ],
    ),
    para(
      s(
        'Satu hal lagi: satu pertanyaan, satu bacaan. Menumpuk tiga pertanyaan ke dalam satu sebaran tiga kartu memaksa setiap kartu menjawab tiga hal sekaligus, dan hasilnya selalu terdengar pintar tapi tidak berguna.',
      ),
    ),

    h2('three-card', 'Sebaran tiga kartu, langkah demi langkah'),
    para(
      s(
        'Sebaran tiga kartu adalah sebaran pertama yang perlu kamu kuasai, dan untuk banyak orang satu-satunya yang pernah dibutuhkan. Tiga kartu berderet, dibaca dari kiri ke kanan:',
      ),
    ),
    steps(
      [
        strong('Yang sudah berlalu.'),
        s(
          ' Apa yang membawa keadaanmu sampai ke titik ini. Bukan sejarah lengkap — satu sebab yang masih terasa.',
        ),
      ],
      [
        strong('Yang sedang berjalan.'),
        s(' Keadaan hari ini, termasuk bagian yang kamu hindari menyebutnya.'),
      ],
      [
        strong('Yang menanti di depan.'),
        s(
          ' Arah yang sedang ditempuh keadaan ini kalau tidak ada yang berubah. Ini bukan ramalan; ini kelanjutan.',
        ),
      ],
    ),
    h3('contoh', 'Satu contoh, utuh'),
    para(
      s('Pertanyaannya: '),
      em('"Apa yang perlu aku lihat tentang pekerjaanku sekarang?"'),
      s(' Kartunya, berurutan: The Moon, The Chariot terbalik, dan Wheel of Fortune.'),
    ),
    cardRef('the-moon', 'The Moon di posisi pertama: sesuatu yang belum jelas, dan belum diakui.'),
    para(
      s(
        'The Moon di posisi pertama. Yang membawa keadaan ini bukan satu peristiwa besar, melainkan sesuatu yang tidak pernah dibicarakan terang-terangan: janji yang samar, peran yang tidak pernah didefinisikan, kesan yang dibiarkan menggantung. Ada yang tidak jelas, dan ketidakjelasan itu sudah lama.',
      ),
    ),
    para(
      s(
        'The Chariot terbalik di tengah. Tegak, The Chariot adalah tenaga yang punya arah. Terbalik, tenaganya masih ada dan arahnya hilang: kamu bekerja keras dan tidak merasa bergerak. Perhatikan bahwa kartu ini menjawab kartu sebelumnya — sulit menuju ke suatu tempat yang tidak pernah disebutkan.',
      ),
    ),
    para(
      s(
        'Wheel of Fortune di posisi ketiga. Perubahan yang datang dari luar, dan lebih cepat daripada rencanamu. Bukan hadiah, bukan hukuman: pergeseran. Kalau ketidakjelasan itu tidak diselesaikan sebelum roda berputar, ia akan diselesaikan oleh keadaan, tanpa bertanya kepadamu.',
      ),
    ),
    para(
      strong('Dirangkai:'),
      s(
        ' sesuatu yang tidak pernah diperjelas telah menguras tenagamu tanpa memindahkanmu, dan keadaannya akan berubah dari luar. Yang bisa kamu lakukan sekarang adalah memaksa satu percakapan yang jelas sebelum perubahan itu memilih untukmu.',
      ),
    ),
    para(
      s('Perhatikan apa yang '),
      em('tidak'),
      s(
        ' dilakukan bacaan itu. Ia tidak menyebut bulan, tidak menyebut nama, dan tidak mengatakan kamu akan dipromosikan. Ia menyebut satu hal yang bisa kamu kerjakan besok. Bacaan yang baik hampir selalu berakhir di sesuatu yang bisa dikerjakan.',
      ),
    ),

    h2('reversals', 'Kartu terbalik'),
    para(
      s(
        'Kartu yang keluar terbalik tidak berarti kebalikan dari kartu itu, dan tidak berarti kabar buruk. Ia mengucapkan pernyataan yang lain.',
      ),
    ),
    para(
      s(
        'The Star tegak: harapan yang pelan, tenang, dan cukup. The Star terbalik bukan "tidak ada harapan" — lebih sering ia berarti harapan yang kamu simpan begitu rapat sampai tidak pernah kamu uji. Pernyataan yang berbeda, dari gambar yang sama, dilihat dari sudut yang lain.',
      ),
    ),
    para(
      s(
        'Kalau kamu baru mulai, boleh saja membaca semua kartu dalam posisi tegak selama beberapa bulan. Tambahkan kartu terbalik ketika kamu sudah mengenal ke-22 kartu itu dalam posisi tegak, karena kartu terbalik menuntut kamu tahu lebih dulu apa yang sedang dibalik.',
      ),
    ),

    h2('stringing', 'Merangkai kartu menjadi satu cerita'),
    para(
      s(
        'Ini yang memisahkan orang yang membaca kartu dari orang yang menghafal arti kartu. Tiga kebiasaan, dan ketiganya bisa dilatih.',
      ),
    ),
    bullets(
      [
        strong('Baca barisnya sebagai satu kalimat.'),
        s(
          ' Kalau tiga kartu itu tidak bisa kamu ucapkan dalam satu kalimat yang masuk akal, kamu belum membaca sebarannya — kamu baru membaca tiga kartu yang kebetulan berdekatan.',
        ),
      ],
      [
        strong('Perhatikan yang berulang.'),
        s(
          ' Dua kartu dengan elemen api berturut-turut mengeraskan nada bacaan. Dua kartu dari tahap awal perjalanan mengatakan bahwa persoalannya lebih muda daripada yang kamu duga. Ulangan adalah penekanan.',
        ),
      ],
      [
        strong('Perhatikan yang tidak ada.'),
        s(
          ' Pertanyaan tentang uang yang dijawab tiga kartu yang seluruhnya tentang orang lain sudah memberi jawaban, dan jawabannya adalah bahwa persoalannya bukan uang.',
        ),
      ],
    ),

    h2('mistakes', 'Lima kesalahan yang paling sering terjadi'),
    steps(
      [
        strong('Menarik ulang sampai dapat jawaban yang disukai.'),
        s(
          ' Kalau kartu ketiga bisa dibatalkan, tidak ada bacaan yang pernah berarti apa pun. Tutup sebarannya, lalu tinggalkan.',
        ),
      ],
      [
        strong('Menanyakan hal yang sama dua kali dalam sehari.'),
        s(
          ' Pertanyaan yang sama pada hari yang sama akan mendapat jawaban yang sama, hanya dengan gambar yang berbeda. Yang berubah bukan keadaanmu, melainkan kesabaranmu.',
        ),
      ],
      [
        strong('Memutuskan artinya sebelum kartunya dibuka.'),
        s(
          ' Ini kesalahan yang paling sulit dilihat, karena rasanya justru seperti bacaan yang sangat lancar.',
        ),
      ],
      [
        strong('Membaca untuk orang yang tidak meminta.'),
        s(' Sudah disebut di atas, dan sengaja disebut dua kali.'),
      ],
      [
        strong('Menghafal daftar arti dan berhenti melihat gambarnya.'),
        s(' Gambarnya yang bekerja. Daftar arti hanya membantu kamu mulai bicara.'),
      ],
    ),

    h2('practice', 'Cara berlatih'),
    para(
      s(
        'Satu kartu sehari, setiap pagi, tanpa pertanyaan. Tarik satu, lihat gambarnya selama satu menit, tulis tiga hal yang kamu lihat sebelum kamu menulis apa artinya. Malamnya, tulis satu baris tentang bagaimana hari itu berjalan.',
      ),
    ),
    para(
      s(
        'Setelah sebulan kamu punya tiga puluh catatan, dan catatan itu jauh lebih berguna daripada daftar arti mana pun: ia berisi arti kartu-kartu itu ',
      ),
      em('untukmu'),
      s(
        '. Kenali ke-22 Major Arcana dengan cara ini, satu per satu, dan bagian yang paling sulit sudah kamu lewati.',
      ),
    ),

    h2('next', 'Ke mana selanjutnya'),
    para(
      s('Mulailah dari gambarnya. '),
      link('/gallery', 'Galeri Major Arcana'),
      s(' memuat ke-22 kartu dalam satu halaman, dan setiap kartu punya halamannya sendiri: '),
      link('/arcana/the-fool', 'The Fool'),
      s(' untuk melihat dari mana perjalanan ini dimulai, '),
      link('/arcana/the-moon', 'The Moon'),
      s(' untuk kartu yang paling sering disalahpahami, '),
      link('/arcana/death', 'Death'),
      s(' untuk kartu yang paling sering ditakuti, dan '),
      link('/arcana/the-star', 'The Star'),
      s(' untuk kartu yang paling sering dibutuhkan.'),
    ),
    para(
      s(
        'Atau tarik kartu sekarang, dengan satu pertanyaan yang sudah kamu susun mengikuti bagian ',
      ),
      link('#the-question', 'menyusun pertanyaan'),
      s('.'),
    ),
  ],
};
