/**
 * A REAL paste, kept verbatim as a test fixture. **2026-07-31.**
 *
 * Three paragraphs of Indonesian tarot prose, generated by Gemini and pasted into
 * `/admin/blog`'s Konten field by Miftah. It is here because **Auto Format failed on it and
 * every synthetic fixture in the suite passed** — the difference was one property nobody had
 * thought to vary:
 *
 * ```
 *   lines: 3        blank lines: 0
 * ```
 *
 * A chat UI separates paragraphs with ONE newline. Markdown says a single newline continues a
 * paragraph, so `parseMarkdown` joined all three into a single 2,292-character block — and
 * `applyAdvice` can only insert a heading BETWEEN blocks, so a one-block document offers
 * exactly two legal positions. **The model was asked to find the sections of a document that
 * had no internal boundaries, and it returned the same heading three times.**
 *
 * ── WHY IT IS A COMMITTED FIXTURE AND NOT A PARAPHRASE ──────────────────────
 *
 * Every property that made it fail is a property of the real bytes: the newline shape, the
 * paragraph lengths (784/784/722 characters, far longer than any hand-written case), the
 * straight double quotes around `"The Fool"` and `"Rider-Waite"`, the parenthesised `(RWS)`
 * before a full stop, and the fact that every line ends on a sentence boundary — which is the
 * signal `splitRun` now keys on. A shortened version would have lost at least one of them.
 *
 * **`export const` RATHER THAN A `.txt` READ**, so the string is in the bundle the test
 * compiles and no `readFileSync` path can go stale.
 *
 * **It is prose, so `src/content/**`'s copy lint would apply to it** — which is why it lives
 * under `src/lib/content/fixtures/` and not in `src/content/`. It is test INPUT, deliberately
 * un-linted: `pergeseran interpretasi` and the rest are Gemini's words, not ours, and holding
 * a fixture to the standard of published copy would mean editing the evidence.
 */

/** The paste exactly as it arrived: three paragraphs, single newlines, no blank line. */
export const PASTED_ARTICLE_ID = [
  'Melanjutkan konsep "Perjalanan Sang Bodoh" yang telah dibahas sebelumnya, para praktisi tarot modern sering kali membagi 21 kartu Major Arcana (di luar kartu "The Fool") menjadi tiga kelompok besar yang masing-masing terdiri dari tujuh kartu. Pembagian yang dikenal sebagai Three Septenaries ini menggambarkan tiga fase utama dalam perkembangan psikologis dan spiritual manusia. Kelompok pertama (kartu 1 hingga 7) melambangkan fase kesadaran fisik, ego, dan sosialisasi di dunia material. Kelompok kedua (kartu 8 hingga 14) mewakili perjalanan ke dalam diri untuk memahami moralitas, intuisi, dan hukum alam. Sementara kelompok ketiga (kartu 15 hingga 21) melambangkan fase transendental, di mana manusia menghadapi ketakutan terdalamnya sebelum akhirnya mencapai keutuhan spiritual.',
  'Perkembangan visual Major Arcana juga menyimpan catatan sejarah yang menyoroti kontribusi penting seorang seniman yang sempat terlupakan. Dek Tarot yang paling populer digunakan di seluruh dunia saat ini adalah dek Rider-Waite-Smith (RWS) yang diterbitkan pada tahun 1909. Ilustrasi ikonik pada kartu-kartu Major Arcana tersebut dilukis oleh seorang seniman perempuan bernama Pamela Colman Smith. Meskipun karya seni visualnya yang kaya akan simbolisme menjadi standar interpretasi tarot modern, namanya sempat diabaikan selama puluhan tahun karena dek tersebut awalnya hanya dinamai "Rider-Waite" (merujuk pada penerbit Rider dan penggagas konsepnya, Arthur Edward Waite). Baru pada beberapa dekade terakhir, nama "Smith" disematkan secara resmi untuk menghargai kontribusi besarnya.',
  'Selain kartu "Death" yang telah diulas sebelumnya, terdapat beberapa kartu Major Arcana lain yang maknanya kerap mengalami pergeseran interpretasi. Kartu "The Lovers" (Para Pecinta), misalnya, pada dek-dek klasik abad pertengahan sebenarnya lebih menekankan pada tema pilihan sulit atau persimpangan jalan moral, bukan sekadar romansa cinta seperti anggapan populer saat ini. Begitu pula dengan kartu "The Devil" (Iblis) yang sering kali memicu kekhawatiran saat muncul dalam sesi pembacaan. Dalam pendekatan psikologis, kartu ini tidak melambangkan kekuatan mistis jahat, melainkan representasi dari keterikatan yang tidak sehat, ketergantungan material, atau batasan pikiran yang sebenarnya diciptakan oleh diri sendiri.',
].join('\n');

/** The three paragraphs on their own, for asserting the parse recovered exactly them. */
export const PASTED_PARAGRAPHS = PASTED_ARTICLE_ID.split('\n');

/**
 * The same prose with blank lines, which is what a markdown-aware source produces.
 * **The parse must agree on both**, and that agreement is the fix's whole claim.
 */
export const PASTED_ARTICLE_BLANK_LINES = PASTED_PARAGRAPHS.join('\n\n');

/**
 * The same prose hard-wrapped at 78 columns with blank lines between paragraphs — a paste out
 * of a plain-text editor. **This is the shape `splitRun` must NOT split**, and it is here so
 * the fix is pinned from both sides rather than only from the side that was broken.
 */
export const PASTED_ARTICLE_HARD_WRAPPED = PASTED_PARAGRAPHS.map((p) => {
  const out: string[] = [];
  let line = '';
  for (const word of p.split(' ')) {
    if (line !== '' && (line + ' ' + word).length > 78) {
      out.push(line);
      line = word;
    } else {
      line = line === '' ? word : `${line} ${word}`;
    }
  }
  if (line !== '') out.push(line);
  return out.join('\n');
}).join('\n\n');

/**
 * What glm-4.6 actually returned for the one-block document, reconstructed from the output
 * Miftah pasted back. **The same heading three times, one anchor id between them.**
 *
 * Kept as a fixture because it is the shape of a real model failure, and because the
 * validation that refuses it now would have been easy to write as "refuse a repeated `at`" —
 * which is what the first version did, and which this reply passes.
 */
export const REPEATED_HEADING_REPLY = {
  title: '',
  headings: [
    { at: 1, text: 'Three Septenaries', id: 'three-septenaries' },
    { at: 2, text: 'Three Septenaries', id: 'three-septenaries' },
    { at: 3, text: 'Three Septenaries', id: 'three-septenaries' },
  ],
  anchors: [],
  description: '',
};
