import Link from 'next/link';
import { Callout, Clause, LegalDoc, P, SubClause } from '@/components/Legal';
import { OPERATOR } from './operator';

/**
 * Terms & Conditions, English. **THIS VERSION DOES NOT GOVERN** (W7-D20).
 *
 * Natively written, not translated -- the same discipline W6 applied to the
 * reader personas, for the same reason: a translated legal document reads as
 * translated, and this is the page a stranger reads to decide whether to trust
 * the app. Clause 16 says in both versions which one wins.
 *
 * **THE CLAUSE IDS MUST MATCH `terms.id.tsx` EXACTLY.** They are the anchor
 * targets `CLAUSE_FOR` points at, and an English reader refused under 6.2 must
 * land on 6.2 here. `legal.test.ts` fails on any divergence.
 *
 * The same three prohibitions apply as in the Indonesian file: do not renumber
 * clause 6, do not cite a statute nobody has read, and clauses 10, 11 and 12
 * need a lawyer.
 */
export function TermsEn({ effective }: { effective: string }) {
  return (
    <LegalDoc title="Terms & Conditions" effective={effective}>
      <Clause id="1" n="1." title="Who we are">
        <P>
          {OPERATOR.legalName} (&ldquo;we&rdquo;) operates JMTarot, a tarot website you can open at{' '}
          {OPERATOR.domain}{' '}
          and add to your phone&rsquo;s home screen (the &ldquo;Service&rdquo;).
          You can reach us at{' '}
          <a href={`mailto:${OPERATOR.contactEmail}`}>{OPERATOR.contactEmail}</a>.
        </P>
        <P>
          In this document, &ldquo;you&rdquo; means the person using the Service. A
          &ldquo;reading&rdquo; means the text the Service generates after you draw cards. A
          &ldquo;question&rdquo; means the sentence you type yourself before a reading is made.
        </P>
      </Clause>

      <Clause id="2" n="2." title="Accepting these terms, and changing them">
        <P>Using the Service means accepting these terms. If you do not accept them, do not use it.</P>
        <P>
          We can change this document. Material changes are announced in the app and you are asked
          to accept them again before continuing. We record when you accepted and which version.
        </P>
      </Clause>

      <Clause id="3" n="3." title="Age">
        <P>
          <strong>You must be 18 or older.</strong>{' '}When you first sign in you are asked to confirm
          it.
        </P>
        <P>
          The reason is not the cards. The reason is the set of questions we ask once, at the
          start: one of them asks about the worst thing you have witnessed, and we store your
          answer. Collecting that from a fourteen-year-old is a different order of risk, and no
          amount of encryption changes it. Clause 7 explains the whole of it.
        </P>
        <P>
          We do not verify age, and we would rather say so than imply otherwise. If we learn a user
          is under 18, the account is deleted.
        </P>
      </Clause>

      <Clause id="4" n="4." title="What the Service is">
        <Callout>
          <P>
            <strong>This is entertainment.</strong>{' '}Tarot has no predictive power and we do not
            claim it does. Do not make an important decision on the strength of a reading here.
          </P>
        </Callout>
        <SubClause id="4-2" n="4.2" title="Not professional advice">
          <P>
            The Service is not medical, mental-health, psychological, psychiatric, legal,
            financial, tax or relationship advice, and is not a substitute for any of them. Nothing
            here diagnoses, treats or heals anything.
          </P>
        </SubClause>
        <SubClause id="4-3" n="4.3" title="Readings are written by a language model">
          <P>
            Every reading is generated by a large language model at the moment you ask for it. They
            are non-deterministic: the same cards and the same question will give you different
            text. They can be factually wrong, and no human writes or reviews one before you see
            it.
          </P>
        </SubClause>
        <SubClause id="4-4" n="4.4" title="The readers are fictional characters">
          <P>
            Thessaly, Margaret and Adrian are personas, not people. They hold no qualification and
            give no professional opinion.
          </P>
        </SubClause>
        <SubClause id="4-5" n="4.5" title="Nothing is promised">
          <P>We promise no outcome from any reading.</P>
        </SubClause>
      </Clause>

      <Clause id="5" n="5." title="Your account">
        <P>
          Google sign-in only. One account per person. Keeping your Google account secure is your
          responsibility.
        </P>
        <P>
          We identify you by the stable identifier Google gives us, not by your email address, so
          changing your email at Google does not change your account here.
        </P>
      </Clause>

      <Clause id="6" n="6." title="Questions and conduct we will not serve">
        <SubClause id="6-1" n="6.1" title="In general">
          <P>
            The Service refuses questions in the categories below, automatically, and sometimes
            wrongly. <strong>A refusal is not an accusation</strong>{' '}and is not recorded against
            you as a strike. If a reasonable question of yours is refused, rephrase it, or tell us
            at <a href={`mailto:${OPERATOR.contactEmail}`}>{OPERATOR.contactEmail}</a>.
          </P>
          <P>
            The opposite is worth stating too. These are <strong>allowed</strong>, and they are
            tarot&rsquo;s actual subject matter: grief, someone else&rsquo;s death, illness,
            divorce, infidelity, losing a job, debt, legal trouble, curses and{' '}
            <em>santet</em>, and questions about leaving a partner who frightens you.
          </P>
        </SubClause>
        <SubClause id="6-2" n="6.2" title="Self-harm and suicide">
          <P>
            Do not ask the Service to advise on, decide about, encourage, or supply means or timing
            for ending your life or injuring yourself. See clause 7.
          </P>
        </SubClause>
        <SubClause id="6-3" n="6.3" title="Violence against other people">
          <P>
            Do not ask the Service to advise on, decide about, or bless injuring or killing any
            person.
          </P>
        </SubClause>
        <SubClause id="6-4" n="6.4" title="Terrorism and extremism">
          <P>
            No attack planning, no weapon or explosive construction, no glorification of either.
          </P>
        </SubClause>
        <SubClause id="6-5" n="6.5" title="Sexual content involving minors">
          <P>
            Absolute. No exception, no context, no fiction. Always refused &mdash; and unlike every
            other category, the text of the question is not stored at all.
          </P>
        </SubClause>
        <SubClause id="6-6" n="6.6" title="Illegal acts that harm someone">
          <P>
            Poisoning, trafficking, targeted fraud, illegal weapons and the like.{' '}
            <strong>This is not a ban on asking about your own legal trouble</strong>{' '}&mdash; that
            question is welcome.
          </P>
        </SubClause>
        <SubClause id="6-7" n="6.7" title="Hate and dehumanisation">
          <P>
            Attacks on people for their race, religion, ethnicity, nationality, disability, gender
            or sexuality.
          </P>
        </SubClause>
        <SubClause id="6-8" n="6.8" title="Coercion, stalking and consent">
          <P>
            Do not ask the Service to help you follow, pressure, deceive, or override the refusal
            of another person.
          </P>
        </SubClause>
        <SubClause id="6-9" n="6.9" title="Circumventing the Service">
          <P>
            Do not attempt to change, reveal, extract or reproduce the Service&rsquo;s
            instructions, prompts or safety controls, or to make it act outside its role.
          </P>
        </SubClause>
        <SubClause id="6-10" n="6.10" title="Automated access">
          <P>No scraping, no automated querying, no resale of readings, no reverse engineering.</P>
        </SubClause>
      </Clause>

      <Clause
        id="7"
        n="7."
        title="Why we ask about hard things, and then refuse to read cards about them"
      >
        {/* Drafted verbatim in W7's plan §4.2. Natively written, not a translation
            of the Indonesian -- same substance, different sentences. */}
        <P>
          When you first sign in, we ask you something heavy: the worst thing you have ever
          witnessed. You can skip it. If you answer, the answer is encrypted, and only an abstract
          summary of it ever reaches the language model &mdash; never your own words.
        </P>
        <P>
          But if you ask for a reading about ending your life, we refuse. Those two things look
          like a contradiction. They are not.
        </P>
        <P>
          The first is one closed question, asked once, that you are free to leave blank, and that
          we only store. We do not respond to it, judge it, or advise you on it.
        </P>
        <P>
          The second is an open request for guidance about your safety &mdash; and the answer would
          be written by a language model that knows nothing about your situation, cannot check on
          you, and holds no qualification to answer it.
        </P>
        <P>
          <strong>
            We are willing to hold what you tell us. We are not willing to guess at your safety.
          </strong>
        </P>
      </Clause>

      <Clause id="8" n="8." title="Refusal, suspension and ending an account">
        <P>
          We may refuse any question. We may suspend or end an account for repeated, deliberate
          breaches of clause 6.
        </P>
        <P>
          We do not count strikes automatically and we do not ban automatically. Ending an account
          is a decision a person makes after looking at the history.
        </P>
        <P>
          You can close your own account at any time.{' '}
          <Link href="/privacy#8">Privacy policy section 8</Link>{' '}says how, and exactly what is
          deleted.
        </P>
      </Clause>

      <Clause id="9" n="9." title="Intellectual property">
        <P>
          Ours: the card artwork, the reader personas and their writing, the prompts and system
          instructions, the code, and the name JMTarot.
        </P>
        <P>
          Yours: the questions you type, and you keep them. You give us permission to process and
          store your questions and readings as described in the privacy policy, in order to run and
          personalise the Service &mdash; and for nothing else.
        </P>
        <P>Readings are for your own personal, non-commercial use.</P>
      </Clause>

      <Clause id="10" n="10." title="No warranty">
        {/* NEEDS LEGAL REVIEW -- substance drafted, enforceability not assessed. */}
        <P>
          The Service is provided as is. We do not warrant that it will be available, error-free,
          accurate, or fit for any particular purpose.
        </P>
      </Clause>

      <Clause id="11" n="11." title="Limitation of liability">
        {/* NEEDS LEGAL REVIEW -- substance drafted, enforceability not assessed. */}
        <P>
          We are not liable for decisions you take on the basis of a reading, nor for indirect or
          consequential loss arising from your use of the Service.
        </P>
        <P>
          The Service is free, so our liability is capped at a nominal amount. Nothing in this
          clause limits liability that cannot lawfully be limited.
        </P>
      </Clause>

      <Clause id="12" n="12." title="Indemnity">
        {/* NEEDS LEGAL REVIEW -- substance drafted, enforceability not assessed. */}
        <P>
          You agree to indemnify us against loss arising from your use of the Service in breach of
          these terms.
        </P>
      </Clause>

      <Clause id="13" n="13." title="Privacy">
        <P>
          The <Link href="/privacy">privacy policy</Link>{' '}sets out what we collect, why, who else
          sees it, and how long we keep it. It forms part of these terms.
        </P>
      </Clause>

      <Clause id="14" n="14." title="Availability, and changes to the Service">
        <P>
          The Service is free. We may change it or stop offering it. We do not guarantee uptime,
          and we do not guarantee that your data is kept for longer than the retention periods in
          the privacy policy.
        </P>
      </Clause>

      <Clause id="15" n="15." title="Governing law and disputes">
        <P>These terms are governed by the law of the Republic of Indonesia.</P>
        <P>
          The parties elect a general and permanent legal domicile at the registry of the{' '}
          {OPERATOR.forum}.
        </P>
      </Clause>

      <Clause id="16" n="16." title="Language">
        <Callout>
          <P>
            These terms exist in Indonesian and in English.{' '}
            <strong>The Indonesian version governs.</strong>{' '}Where the two differ in meaning, the
            Indonesian version is the one that applies.
          </P>
        </Callout>
      </Clause>

      <Clause id="17" n="17." title="Contact">
        <P>
          {OPERATOR.legalName} &mdash;{' '}
          <a href={`mailto:${OPERATOR.contactEmail}`}>{OPERATOR.contactEmail}</a>
        </P>
      </Clause>
    </LegalDoc>
  );
}
