import { describe, expect, it } from 'vitest';
import { CARDS } from '@/data/deck';
import { SIGNS } from '@/lib/numerology';
import { ATTRIBUTIONS, attributionFor, rootCardFor } from './correspondence';

describe('the glyph attribution table', () => {
  it('covers every card exactly once, with no orphan keys', () => {
    // Twenty-two glyphs, twenty-two cards, and a glyph is a single non-ASCII
    // character in a source file -- so the failure mode is a mojibake key that
    // matches nothing and renders a gap. Assert both directions.
    const used = CARDS.map((c) => c.glyph);
    expect(new Set(used).size).toBe(22);
    expect(Object.keys(ATTRIBUTIONS).sort()).toEqual([...used].sort());
    for (const card of CARDS) {
      expect({ name: card.name, has: attributionFor(card) !== null })
        .toEqual({ name: card.name, has: true });
    }
  });

  it('agrees with cards.json about the element, for all twelve sign cards', () => {
    /*
     * **THE INVARIANT THAT MAKES THE WHOLE TABLE TRUSTWORTHY.** A mistyped glyph
     * almost certainly disagrees with the card's own element, and this names the
     * card when it does. Verified 2026-07-29: all twelve agree with the Golden
     * Dawn attributions and with `SIGNS` in astrology.ts, with no exceptions.
     *
     * The nine planetary cards and The Fool are deliberately NOT asserted:
     * Judgement is `water` in `cards.json` while the Golden Dawn attributes the
     * trump to Fire, and `cards.json` is generated by a script S4 does not own.
     */
    const signCards = CARDS.filter((c) => attributionFor(c)!.sign !== null);
    expect(signCards).toHaveLength(12);
    for (const card of signCards) {
      const sign = attributionFor(card)!.sign!;
      expect({ name: card.name, sign, element: SIGNS[sign].element })
        .toEqual({ name: card.name, sign, element: card.element });
    }
  });

  it('leaves the nine planetary cards and The Fool with no sign, on purpose', () => {
    // V1 has no planet table and this workstream is not inventing one: nine
    // made-up glosses to fill a layout hole is the "vague cosmic language" the
    // v0.3.0 risk table logs against exactly this page. Render nothing for a null
    // (W5's M14 rule).
    const noSign = CARDS.filter((c) => attributionFor(c)!.sign === null);
    expect(noSign.map((c) => c.name).sort()).toEqual([
      'Judgement', 'The Empress', 'The Fool', 'The Hanged Man', 'The High Priestess',
      'The Magician', 'The Sun', 'The Tower', 'The World', 'Wheel of Fortune',
    ]);
  });

  it('names the two luminaries in Latin, so a label never collides with a card name', () => {
    // ☾ is The High Priestess's attribution and `The Moon` is a CARD. Labelling it
    // "The Moon" renders "The High Priestess -- The Moon", and on the lore page for
    // card 18 it renders "The Moon: The Moon". `Luna` and `Sol` are the standard
    // astrological names and they are proper nouns, so they are not translated copy.
    expect(attributionFor(CARDS[2])!.label.en).toBe('Luna');
    expect(attributionFor(CARDS[19])!.label.en).toBe('Sol');
    for (const card of CARDS) {
      const label = attributionFor(card)!.label;
      for (const other of CARDS) {
        expect({ card: card.name, label: label.en, clash: label.en === other.name })
          .toMatchObject({ clash: false });
      }
    }
  });

  it('translates the planets and leaves the signs alone', () => {
    // Sign names are the Latin names in Indonesian too (`Pisces`, not a
    // translation), so those pairs are identical BY DESIGN and that is not a
    // missing translation. Planet names do inflect: Merkurius, Saturnus, Neptunus,
    // Matahari, Bulan.
    expect(attributionFor(CARDS[18])!.label).toEqual({ id: 'Pisces', en: 'Pisces' });
    expect(attributionFor(CARDS[1])!.label).toEqual({ id: 'Merkurius', en: 'Mercury' });
    expect(attributionFor(CARDS[21])!.label).toEqual({ id: 'Saturnus', en: 'Saturn' });
  });
});

describe('the root card', () => {
  it('folds eighteen to The Hermit and ten to The Magician', () => {
    expect(rootCardFor(CARDS[18])!.name).toBe('The Hermit');
    expect(rootCardFor(CARDS[10])!.name).toBe('The Magician');
    expect(rootCardFor(CARDS[21])!.name).toBe('The Empress');
  });

  it('is null for The Fool, for 1-9, and FOR JUSTICE', () => {
    /*
     * **THE JUSTICE CASE IS A TRAP AND IT EXISTS BECAUSE OF v0.3.0
     * RECONCILIATION §5.3.** `reduce(11)` is 11 -- the masters are FIXED POINTS
     * since that amendment -- so Justice's root card is Justice, and rendering
     * "Justice reduces to Justice" is a tautology dressed as a correspondence.
     * Suppressed in the module rather than in the page, so every future consumer
     * inherits the suppression.
     *
     * The Fool is null because `reduce(0)` is 0 and `reduceToGloss(0)` is null:
     * zero is not a numerological quality (see reduce.ts's GlossNumber comment).
     * Cards 1-9 are their own root, which is equally not worth a sentence.
     */
    expect(rootCardFor(CARDS[0])).toBeNull();
    expect(rootCardFor(CARDS[11])).toBeNull();
    for (let id = 1; id <= 9; id++) expect(rootCardFor(CARDS[id])).toBeNull();
  });

  it('has one for exactly eleven cards', () => {
    const withRoot = CARDS.filter((c) => rootCardFor(c) !== null).map((c) => c.id);
    expect(withRoot).toEqual([10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]);
  });
});
