import raw from './cards.json';
import type { Card, Draw, Locale, Polarity } from './types';

export const CARDS = raw as Card[];

/**
 * BUMP THIS EVERY TIME THE ART IS REGENERATED. It is the whole cache story.
 *
 * `next.config.ts` serves `/cards/*` with `max-age=31536000, immutable` on
 * SLUG-BASED, NON-CONTENT-HASHED filenames, and says in as many words that
 * regenerating means changing the filenames or shortening that header first.
 * Neither is necessary: appending a version to the URL makes it a different
 * resource to every cache, while leaving `immutable` completely honest -- any
 * given `?v=N` really never changes.
 *
 * Chosen over the alternatives on purpose. Content-hashing 44 filenames would
 * mean a generated registry, which is the `cardArt.ts` the web rewrite deleted.
 * Shortening the header would pay for one regeneration by giving up caching
 * forever, for art that changes about once a year.
 *
 * v1 -> v2: the deck regenerated by `/generate-tarot-card`. Full bleed (the old
 * cards 0-10 lost 11% of their width to black bars), one consistent frame
 * treatment, and NO TEXT -- `CardFace` draws the name now.
 * v2 -> v3: The Empress redrawn. She had two arms on her left and none on her
 * right. ONE CARD CHANGING IS ENOUGH TO BUMP THIS -- the filename did not change,
 * so without it every existing install keeps the three-armed one for a year.
 */
const ART_VERSION = 3;

/**
 * Full-size card art, 800x1200. For the result panel, where the card is large
 * enough that the artwork is the point.
 *
 * The iOS build needed a generated `cardArt.ts` registry here because Metro
 * cannot resolve a computed `require` path. On the web the URL is the lookup,
 * so the registry is gone and the slug is the only key we need.
 */
export function cardImage(slug: string): string {
  return `/cards/${slug}.webp?v=${ART_VERSION}`;
}

/**
 * 240x360 card art, ~13KB. For the fan and the slots, which draw at 88x132.
 * Serving the full size to 22 fanned cards would cost 3.7MB to paint
 * thumbnails -- see tools/normalize_cards.py.
 */
export function cardThumb(slug: string): string {
  return `/cards/thumb/${slug}.webp?v=${ART_VERSION}`;
}

/** The design reverses roughly three cards in ten. */
const REVERSAL_RATE = 0.3;

/**
 * Shuffle the full deck, then assign orientations.
 *
 * The shuffle happens before the user picks anything and every card is face
 * down, so which card sits at which arc position is genuinely arbitrary. That
 * matters: it means the pick is a real draw, not a reveal chosen after the fact.
 */
export function shuffleDeck(reversals = true): Draw[] {
  const order = [...CARDS];
  for (let i = order.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [order[i], order[j]] = [order[j], order[i]];
  }
  return order.map((card) => ({
    card,
    reversed: reversals && Math.random() < REVERSAL_RATE,
  }));
}

/**
 * One card by its Major Arcana number, or `undefined`.
 *
 * A LOOKUP, NOT `CARDS[id]`, and the difference is not pedantry: indexing is
 * correct only while the array happens to be in id order, and nothing enforces
 * that -- `cards.json` is generated, and a generator that ever emits a different
 * order would silently start rendering the wrong card under the right name. That
 * is the same shape as the bug that once showed The Fool while requesting id 15.
 *
 * `undefined` rather than a throw, because every caller is a renderer: V6's
 * history reconstructs a draw from `reading_cards` rows, and a row naming a card
 * that no longer exists is a gap in a list, not a crash on a page that has
 * already sent its headers.
 */
export function cardById(id: number): Card | undefined {
  return CARDS.find((c) => c.id === id);
}

/**
 * The one line shown under a card in the detail overlay.
 *
 * Orientation decides which of the two lines is true, the same way it decides
 * polarity and the yes/no verdict. Going through this function rather than
 * reading `card.meaning.upright` is what keeps a reversed card from being
 * described as if it were upright -- and now what keeps an English querent from
 * being handed the Indonesian line. There are two ways to get this wrong by hand
 * instead of one, which makes the indirection worth more than it was.
 */
export function cardMeaning({ card, reversed }: Draw, locale: Locale): string {
  const pair = card.meaning[locale];
  return reversed ? pair.reversed : pair.upright;
}

/**
 * The three keywords, in one locale.
 *
 * Same argument as `cardMeaning`, and the same reason it is a function rather
 * than a property read: these go to the model as grounding in the user turn, so a
 * locale mismatch here does not render wrongly, it makes the prompt disagree with
 * the reading it asks for.
 */
export function cardKeywords(card: Card, locale: Locale): string[] {
  return card.keywords[locale];
}

/** Reversal inverts a card's charge. Neutral cards have none to invert. */
export function effectivePolarity({ card, reversed }: Draw): Polarity {
  if (!reversed || card.polarity === 'neutral') return card.polarity;
  return card.polarity === 'light' ? 'shadow' : 'light';
}

/** A reversal also flips a yes into a no. `maybe` stays undecided either way. */
export function effectiveYesNo({ card, reversed }: Draw) {
  if (!reversed || card.yesno === 'maybe') return card.yesno;
  return card.yesno === 'yes' ? 'no' : 'yes';
}

/**
 * The querent's birth card, by the usual reduction: sum every digit of the
 * birth date, then fold the total until it lands in 0-21.
 *
 * Deterministic and offline, and it maps cleanly onto our deck because our deck
 * *is* the 22 Majors.
 */
export function birthCard(isoDate: string): Card {
  const digits = isoDate.replace(/\D/g, '');
  let total = 0;
  for (const ch of digits) total += Number(ch);
  while (total > 21) {
    let folded = 0;
    for (const ch of String(total)) folded += Number(ch);
    if (folded === total) break;
    total = folded;
  }
  return CARDS[Math.min(total, 21)];
}

/**
 * The card's PUBLIC URL slug (v0.4.0, S-D4). `the-moon`, never `18_moon`.
 *
 * **A SECOND IDENTIFIER, DELIBERATELY, AND THE TWO MUST NEVER BE MERGED.**
 * `Card.slug` addresses a FILE: it matches the art filename and twenty-two
 * committed assets under `public/cards/` depend on it, which is why `cardImage()`
 * and `cardThumb()` interpolate it. This one addresses a DOCUMENT somebody found
 * by typing words. An underscore and a leading number are worth nothing in a URL
 * and cost a keyword; a hyphenated English name is the query.
 *
 * **IDENTICAL IN BOTH LOCALES, BECAUSE CARD NAMES ARE** (`## Card data`,
 * `## Localization` rule 1). That is what makes the `hreflang` pair a clean
 * `/arcana/X` <-> `/en/arcana/X` mapping with no per-locale slug table -- S-D4's
 * own reason, and it is load-bearing for `contentAlternates()`.
 *
 * **NO SPECIAL CASES, AND `urlSlug.test.ts` ASSERTS THERE ARE NONE.** Four cards
 * carry no article (`strength`, `justice`, `death`, `temperance`) and
 * `Wheel of Fortune` keeps its `of`; both fall out of lowercasing and hyphenating.
 * `Judgement` keeps the British spelling because the card does.
 *
 * DERIVED RATHER THAN TABULATED, and asserted against a committed table. A
 * hand-written map would be twenty-two chances to typo an address that can never
 * change; a derivation plus a table test is one function and one list a reviewer
 * can read.
 */
export function cardUrlSlug(card: Card): string {
  return card.name.toLowerCase().replace(/\s+/g, '-');
}

/**
 * The twenty-two URL slugs, in Fool's Journey order.
 *
 * For `generateStaticParams`. **A `readonly string[]` and not a literal union**:
 * `cards.json` is generated, so there is nothing to derive a union from at compile
 * time, and the guarantee lives in `urlSlug.test.ts` instead -- the same place the
 * address contract already lives.
 *
 * **`src/app/sitemap.ts` TAKES `LORE_SLUGS` FROM THE REGISTRY AND NOT THIS.**
 * While the forty-four documents are being written, advertising a URL whose
 * document does not exist is telling a crawler about a 404.
 */
export const CARD_URL_SLUGS: readonly string[] = CARDS.map(cardUrlSlug);

/**
 * One card by its URL slug, or `undefined`.
 *
 * `undefined` rather than a throw, for exactly `cardById`'s reason: every caller
 * is a renderer, and the page turns the miss into `notFound()` where it can still
 * send a status. Case-sensitive and exact -- `/arcana/The-Moon` is a different URL
 * and must 404 rather than quietly serving the same document at a second address,
 * which is a duplicate a crawler has to choose between.
 */
export function cardByUrlSlug(slug: string): Card | undefined {
  return CARDS.find((c) => cardUrlSlug(c) === slug);
}
